### ISSUE TITLE
MQTT Broker port specified in config.py not used by gardenalocalcontrol.py

### ISSUE THREAD

**Issue by tuinstoelen** [andrexp/gardena-local-control#23]
Hi AndreXP, 

Thank you for creating gardena-local-control, it is exactly what I was looking for! I've managed to successfully get it up and running on my Gardena smart gateway 19005. Nice of Gardena / Husqvarna that they did not try and lock it down. Soon I will have the sensor graphs incorporated into Domoticz :)

During getting the script up and running, I noticed that the port specified in the config.py file is not correctly used. I've created a patch, it is attached. 

[broker-port-fix.patch](https://github.com/user-attachments/files/16497515/broker-port-fix.patch)

Kind regards,

Tuinstoelen

**Comment by andrexp** [comment]
Hi!

Nice to see, that our script is useful to others. You might create a pull request from your fork to our repo so we can see if your changes might be helpful. And yes, since we created the early version of the script no hard work followed on it yet.... For now, the script is working fine for us and we spent some minutes everytime the script stopped working (last time python were upgraded during Gardena gateway update) but that's all. So be sure any optimization suggestions are more than welcome :-) 

Bigger repos have some manual for that, but for us this issue in connection to the PR should be enough. I think there must be some good tutorials on Google or YouTube if you need help.

**Comment by andrexp** [comment]
Hm.. interesting. I just noticed, that you committed directly to our main branch.... Maybe there are some settings missing on my side. Normally this should be forbidden. Thank you for revealing this :-D

**Comment by andrexp** [comment]
My fault. Everything was correct. I did not notice, that I was looking on your fork. As I am on vacation right now I was browsing with my mobile. So everything was a bit small on the screen...

**Comment by FredBit90** [comment]
Hi @tuinstoelen, thanks for your patch to our gardena-local-control project. 
I have created a pull request from your repository back into our repository and will transfer it accordingly. If you notice any other issues, simply fork again and create a new pull request.
